FROM python:latest

WORKDIR /app

RUN apt-get update && apt-get -y install libxml2 unixodbc-dev curl apt-transport-https debconf-utils

RUN curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add -
RUN curl https://packages.microsoft.com/config/debian/10/prod.list > /etc/apt/sources.list.d/mssql-release.list

RUN apt-get update && ACCEPT_EULA=Y apt-get install -y msodbcsql17 unixodbc-dev

RUN pip install faker pyodbc python-dotenv prettytable

CMD ["python", "/app/main.py"]
